### ISSUE TITLE
Two icons libraries

### ISSUE THREAD

**Issue by do-diegoortiz** [MalihaKabir/LandingPageUsingReact#1]
Hi @MalihaKabir, I found your template very useful, I wanted to know why are you using two icons library instead of only one for optimization. Especially since that few are used.

Another question is why do you use two different package.json and how do you connect to each other?

Last but not least, why are you including the vendor and scss files in the public directory?. When I learned we were not supposed to include scss files in the public directory 🤔 

I would really appreciate your help with those questions, especially the part of the packages is very confusing for me because I don't know which of both should I keep adding packages.

**Comment by MalihaKabir** [comment]
Hey @do-diegoortiz, I'm glad that you've found something in my repositories that is useful for you. And thank you so much for notifying me about these improvement areas. Now I'll try my best to clear all of your confusions.

When I was creating this project, I was just learning about react and I wanted to convert any kind of bootstrap web page into a reactjs project. In order to do that, I've used **[a bootstrap portfolio page](https://github.com/BlackrockDigital/startbootstrap-stylish-portfolio)** and added most of the files from this repo to one of my folders and named it as 'public' folder. Hope this bootstrap file will help you more. And whatever I created are in the 'src' folder. This was just an experimental project to explore my knowledge I've learned during that period of my time.

So, you can use any kind of icons library that is necessary for your project. By the way,'package.json' files from both folders worked fine then. But if you're talking about "package.json" and "package-lock.json" then I'd like to let you know that usually when you have a package lock, you are locking the version. This means you don't want to upgrade the version of the package. The "package-lock.json" auto creates with "package.json" to make sure everything is locked.

Now you can do any of these three things- you can either use the [original bootstrap repo](https://github.com/BlackrockDigital/startbootstrap-stylish-portfolio) for your project and manipulate in whichever way you like or take manipulate it by your own by adding all the dependencies in the package.json file that is in the 'src' folder to see how it works and if it does well then delete the package.json file that is in the 'public' folder or you can wait till I update it and make it more usable. I'll get free time after this Saturday. In the meantime, you can also experiment even with both projects and may come up with a new one, who knows.

**Comment by MalihaKabir** [comment]
Hello @do-diegoortiz! If you still face any other challenges related to this one or my other projects, feel free to share it with me. I'd love to help as much as I can.
